-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'HR_MANAGER', 'DEPARTMENT_MANAGER', 'EMPLOYEE', 'GUEST');

-- CreateEnum
CREATE TYPE "StatusAktif" AS ENUM ('TIDAK_AKTIF', 'AKTIF');

-- CreateEnum
CREATE TYPE "JenisKelamin" AS ENUM ('LAKILAKI', 'PEREMPUAN');

-- CreateEnum
CREATE TYPE "StatusKaryawan" AS ENUM ('TETAP', 'KONTRAK', 'PERCOBAAN', 'HONORER', 'OUTSOURCING');

-- CreateEnum
CREATE TYPE "StatusPernikahan" AS ENUM ('BELUM_MENIKAH', 'MENIKAH', 'JANDA', 'DUDA');

-- CreateEnum
CREATE TYPE "JenisPotongan" AS ENUM ('PINJAMAN', 'KOPERASI', 'BPJS', 'PPH21', 'LAINNYA');

-- CreateEnum
CREATE TYPE "JenisTunjangan" AS ENUM ('TRANSPORT', 'MAKAN', 'JABATAN', 'KELUARGA', 'KHUSUS', 'RAPEL');

-- CreateEnum
CREATE TYPE "StatusCuti" AS ENUM ('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "TipeHari" AS ENUM ('KERJA', 'LIBUR', 'LIBUR_NASIONAL', 'CUTI_BERSAMA');

-- CreateEnum
CREATE TYPE "ShiftType" AS ENUM ('PAGI', 'SIANG', 'MALAM', 'LIBUR');

-- CreateTable
CREATE TABLE "AccountEmail" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AccountEmail_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "name" TEXT,
    "image" TEXT,
    "role" "UserRole" NOT NULL DEFAULT 'EMPLOYEE',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Account" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "access_token" TEXT,
    "refresh_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,
    "type" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "company" (
    "id" UUID NOT NULL,
    "KODE_CMPY" CHAR(3) NOT NULL,
    "COMPANY" VARCHAR(40),
    "ADDRESS1" VARCHAR(40),
    "ADDRESS2" VARCHAR(40),
    "ADDRESS3" VARCHAR(40),
    "TLP" VARCHAR(15),
    "FAX" VARCHAR(15),
    "NPWP" VARCHAR(20),
    "DIRECTOR" VARCHAR(25),
    "NPWPDIR" VARCHAR(20),
    "LOGO" VARCHAR(80),
    "NPP" VARCHAR(30),
    "ASTEKBAYAR" VARCHAR(80),
    "EMAIL" VARCHAR(30),
    "HOMEPAGE" VARCHAR(50),
    "HRDMNG" VARCHAR(30),
    "NPWPMNG" VARCHAR(20),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "company_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mstfact" (
    "CKD_FACT" VARCHAR(20) NOT NULL,
    "CNM_FACT" VARCHAR(30),
    "KETERANGAN" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "mstfact_pkey" PRIMARY KEY ("CKD_FACT")
);

-- CreateTable
CREATE TABLE "mstbag" (
    "CKD_BAG" VARCHAR(20) NOT NULL,
    "CNM_BAG" VARCHAR(30),
    "KETERANGAN" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "mstbag_pkey" PRIMARY KEY ("CKD_BAG")
);

-- CreateTable
CREATE TABLE "mstdept" (
    "id" UUID NOT NULL,
    "CKD_BAG" VARCHAR(20),
    "CKD_DEPT" VARCHAR(20) NOT NULL,
    "CNM_DEPT" VARCHAR(30),
    "KETERANGAN" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "mstdept_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mstsie" (
    "id" UUID NOT NULL,
    "CKD_BAG" VARCHAR(20),
    "CKD_DEPT" VARCHAR(20),
    "CKD_SIE" VARCHAR(6) NOT NULL,
    "CNM_SIE" VARCHAR(30),
    "KETERANGAN" VARCHAR(80),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "mstsie_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mstjab" (
    "CKD_JAB" VARCHAR(20) NOT NULL,
    "CNM_JAB" VARCHAR(30),
    "NTJABATAN" DECIMAL(12,0),
    "NTRANSPORT" DECIMAL(12,0),
    "NSHIFT_ALL" DECIMAL(12,0),
    "NPREMI_HDR" DECIMAL(12,0),
    "PERSEN_RMH" DECIMAL(5,2),
    "PERSEN_PPH" DECIMAL(5,2),
    "KETERANGAN" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "mstjab_pkey" PRIMARY KEY ("CKD_JAB")
);

-- CreateTable
CREATE TABLE "mstpkt" (
    "CKD_PKT" VARCHAR(5) NOT NULL,
    "CNM_PKT" VARCHAR(30),
    "KETERANGAN" VARCHAR(30),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "mstpkt_pkey" PRIMARY KEY ("CKD_PKT")
);

-- CreateTable
CREATE TABLE "mstagm" (
    "CKD_AGM" VARCHAR(2) NOT NULL,
    "CNM_AGM" VARCHAR(30),
    "KETERANGAN" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "mstagm_pkey" PRIMARY KEY ("CKD_AGM")
);

-- CreateTable
CREATE TABLE "mstskl" (
    "CKD_SKL" VARCHAR(2) NOT NULL,
    "CNM_SKL" VARCHAR(30),
    "KETERANGAN" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "mstskl_pkey" PRIMARY KEY ("CKD_SKL")
);

-- CreateTable
CREATE TABLE "bank" (
    "BANK_CODE" CHAR(2) NOT NULL,
    "BANK_NAMA" VARCHAR(30),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "bank_pkey" PRIMARY KEY ("BANK_CODE")
);

-- CreateTable
CREATE TABLE "karyawan" (
    "id" UUID NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(16),
    "ID_ABSEN" VARCHAR(9),
    "NAMA" VARCHAR(50) NOT NULL,
    "KD_CMPY" CHAR(3),
    "KD_FACT" VARCHAR(2),
    "KD_BAG" VARCHAR(20),
    "KD_DEPT" VARCHAR(20),
    "KD_SEKSIE" VARCHAR(6),
    "KD_PKT" VARCHAR(5),
    "KD_JAB" VARCHAR(20),
    "KD_AGM" VARCHAR(2),
    "KD_SKL" VARCHAR(2),
    "BANK_CODE" CHAR(2),
    "KD_SEX" "JenisKelamin" DEFAULT 'LAKILAKI',
    "ALAMAT1" VARCHAR(100),
    "ALAMAT2" VARCHAR(100),
    "KOTA" VARCHAR(30),
    "KD_POS" VARCHAR(5),
    "TELPON" VARCHAR(16),
    "HANDPHONE" VARCHAR(16),
    "EMAIL" VARCHAR(50),
    "TMP_LHR" VARCHAR(30),
    "TGL_LHR" DATE,
    "TGL_ANGKAT" DATE,
    "KTPNO" VARCHAR(20),
    "VALID_KTP" DATE,
    "NPWP" VARCHAR(20),
    "TGL_NPWP" DATE,
    "TYPE_SIM" VARCHAR(2),
    "NO_SIM" VARCHAR(20),
    "VALID_SIM" DATE,
    "PASPORTNO" VARCHAR(20),
    "KITASNO" VARCHAR(20),
    "VALID_KITAS" DATE,
    "NOBPJSTK" VARCHAR(20),
    "NOBPJSKES" VARCHAR(20),
    "KD_BPJSTK" BOOLEAN DEFAULT true,
    "KD_BPJSKES" BOOLEAN DEFAULT true,
    "TGL_ASTEK" DATE,
    "BANK_UNIT" VARCHAR(30),
    "BANK_REKNO" VARCHAR(20),
    "BANK_REKNAME" VARCHAR(30),
    "TGL_MSK" DATE,
    "TGL_OUT" DATE,
    "ALASAN_OUT" VARCHAR(100),
    "KD_OUT" BOOLEAN DEFAULT false,
    "KD_JNS" "StatusKaryawan" DEFAULT 'TETAP',
    "HARI_KERJA" INTEGER DEFAULT 5,
    "GROUP_SHIFT" VARCHAR(2) DEFAULT '00',
    "KD_GAJI" INTEGER DEFAULT 1,
    "KD_WNI" BOOLEAN DEFAULT true,
    "KD_STS" "StatusAktif" DEFAULT 'AKTIF',
    "TGL_NIKAH" DATE,
    "KD_PTKP" INTEGER DEFAULT 1,
    "JMLANAK" INTEGER DEFAULT 0,
    "KD_LMB" BOOLEAN DEFAULT true,
    "KD_SPL" BOOLEAN DEFAULT true,
    "KD_PJK" BOOLEAN DEFAULT true,
    "TYPE_PJK" INTEGER DEFAULT 1,
    "KD_JAM" VARCHAR(2) DEFAULT 'A',
    "KD_KOPERASI" BOOLEAN DEFAULT false,
    "KDPT_RUMAH" BOOLEAN DEFAULT false,
    "POT_RUMAH" DECIMAL(5,0) DEFAULT 0,
    "TGL_KOPERASI" DATE,
    "No_ANGGOTA" VARCHAR(9),
    "KD_SPSI" BOOLEAN DEFAULT false,
    "UNIFORM1" CHAR(3),
    "UNIFORM2" DECIMAL(4,0) DEFAULT 0,
    "GLDARAH" VARCHAR(2),
    "TINGGI" DECIMAL(3,0) DEFAULT 0,
    "BERAT" DECIMAL(5,2) DEFAULT 0,
    "POKOK_BLN" DECIMAL(12,0) DEFAULT 0,
    "TTRANSPORT" DECIMAL(12,0) DEFAULT 0,
    "KD_TRANSP" BOOLEAN DEFAULT true,
    "TMAKAN" DECIMAL(12,0) DEFAULT 0,
    "KD_MAKAN" BOOLEAN DEFAULT true,
    "TJABATAN" DECIMAL(12,0) DEFAULT 0,
    "TKELUARGA" DECIMAL(12,0) DEFAULT 0,
    "TKOMUNIKASI" DECIMAL(12,0) DEFAULT 0,
    "TKHUSUS" DECIMAL(12,0) DEFAULT 0,
    "TLMBTETAP" DECIMAL(12,0) DEFAULT 0,
    "FIXOTHER" DECIMAL(12,0) DEFAULT 0,
    "NM_TEMAN" VARCHAR(30),
    "ALM_TEMAN" VARCHAR(40),
    "TLP_TEMAN" VARCHAR(12),
    "HUB_TEMAN" VARCHAR(10),
    "LOKASIPOTO" VARCHAR(100),
    "KKNO" VARCHAR(20),
    "IBUKANDUNG" VARCHAR(50),
    "ALAMATDOM1" VARCHAR(200),
    "ALAMATDOM2" VARCHAR(200),
    "ImagesName" VARCHAR(100),
    "ImagesSize" VARCHAR(50),
    "created_by" VARCHAR(50),
    "updated_by" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,
    "deleted_at" TIMESTAMP,
    "jnsJamKdJam" VARCHAR(2),

    CONSTRAINT "karyawan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "keluarga" (
    "id" UUID NOT NULL,
    "CHILD_NO" INTEGER NOT NULL DEFAULT 0,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10),
    "NAMA" VARCHAR(35),
    "SEX" CHAR(1) DEFAULT 'L',
    "KD_HUB" INTEGER DEFAULT 1,
    "TMP_LAHIR" VARCHAR(15),
    "TGL_LAHIR" DATE,
    "PEKERJAAN" VARCHAR(40),
    "PHOTO" VARCHAR(80),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "keluarga_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sekolah" (
    "id" UUID NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "CHILD_NO" INTEGER NOT NULL DEFAULT 0,
    "NIK" VARCHAR(10),
    "TINGKAT" VARCHAR(2),
    "TEMPAT" VARCHAR(50),
    "THN_MSK" INTEGER DEFAULT 2000,
    "THN_LULUS" INTEGER DEFAULT 2000,
    "KETERANGAN" VARCHAR(60),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "sekolah_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kursus" (
    "id" UUID NOT NULL,
    "CHILD_NO" INTEGER NOT NULL DEFAULT 0,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10),
    "NM_KURSUS" VARCHAR(40),
    "PERIODE1" DATE,
    "PERIODE2" DATE,
    "KET_KURSUS" VARCHAR(40),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "kursus_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kerja" (
    "id" UUID NOT NULL,
    "CHILD_NO" INTEGER NOT NULL DEFAULT 0,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10),
    "PERIODE" VARCHAR(20),
    "COMPANY" VARCHAR(40),
    "JABATAN" VARCHAR(10),
    "JOBDESC" VARCHAR(80),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "kerja_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kontrak" (
    "id" UUID NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10),
    "TGL_MULAI" DATE NOT NULL,
    "TGL_AKHIR" DATE,
    "KETERANGAN" VARCHAR(60),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "kontrak_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "kondite" (
    "id" UUID NOT NULL,
    "CHILD_NO" INTEGER NOT NULL DEFAULT 0,
    "NO_SURAT" VARCHAR(40),
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "TAHUN" INTEGER DEFAULT 2000,
    "NIK" VARCHAR(10),
    "TGL_SURAT" DATE,
    "KD_SIFAT" INTEGER DEFAULT 0,
    "PERIHAL" VARCHAR(40),
    "KETERANGAN" VARCHAR(80),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "kondite_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mutasi" (
    "id" UUID NOT NULL,
    "TGL_MUTASI" DATE NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10),
    "NAMA" VARCHAR(30),
    "FACT_ASAL" VARCHAR(2),
    "BAG_ASAL" VARCHAR(2),
    "DEPT_ASAL" VARCHAR(2),
    "FACT_BARU" VARCHAR(2),
    "BAG_BARU" VARCHAR(2),
    "DEPT_BARU" VARCHAR(2),
    "REMARK" VARCHAR(100),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "mutasi_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pesangon" (
    "id" UUID NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10),
    "TGL_BAYAR" DATE,
    "TGL_PENSIUN" DATE,
    "MS_KERJA" INTEGER DEFAULT 0,
    "JML_PESANGON" DECIMAL(15,0) DEFAULT 0,
    "PENGHARGAAN" DECIMAL(15,0) DEFAULT 0,
    "PPH" DECIMAL(15,0) DEFAULT 0,
    "TOTAL_TERIMA" DECIMAL(15,0) DEFAULT 0,
    "KETERANGAN" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "pesangon_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "absent" (
    "id" UUID NOT NULL,
    "PERIODE" VARCHAR(6) NOT NULL DEFAULT '',
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "TGL_ABSEN" DATE NOT NULL,
    "NIK" VARCHAR(10),
    "ID_ABSEN" VARCHAR(9),
    "NAMA" VARCHAR(30),
    "KD_CMPY" VARCHAR(3),
    "KD_FACT" VARCHAR(2),
    "KD_BAG" VARCHAR(2),
    "KD_DEPT" VARCHAR(2),
    "KD_SEKSIE" VARCHAR(6),
    "KD_JAM" VARCHAR(2),
    "GROUP_SHIFT" CHAR(2) DEFAULT '',
    "STDMASUK" VARCHAR(5),
    "STDKELUAR" VARCHAR(5),
    "REALMASUK" VARCHAR(5),
    "REALKELUAR" VARCHAR(5),
    "JMASUK" VARCHAR(5),
    "JKELUAR" VARCHAR(5),
    "KD_LMB" BOOLEAN DEFAULT false,
    "KD_SPL" BOOLEAN DEFAULT true,
    "LEMBUR1" DECIMAL(6,2) DEFAULT 0.00,
    "LEMBUR2" DECIMAL(6,2) DEFAULT 0.00,
    "LEMBUR3" DECIMAL(6,2) DEFAULT 0.00,
    "LEMBUR4" DECIMAL(6,2) DEFAULT 0.00,
    "TOTKERJA" DECIMAL(6,2) DEFAULT 0.00,
    "LAMBAT" INTEGER DEFAULT 0,
    "CEPAT" INTEGER DEFAULT 0,
    "KD_HARI" INTEGER DEFAULT 1,
    "KD_ABSEN" CHAR(1) DEFAULT 'H',
    "KD_SHIF" INTEGER DEFAULT 1,
    "MSK_LMB" VARCHAR(5),
    "KLR_LMB" VARCHAR(5),
    "TOT_LMB" DECIMAL(7,2) DEFAULT 0.00,
    "KET_LMB" VARCHAR(30),
    "FLAG_SHIFT" BOOLEAN DEFAULT false,
    "FLAG_MEAL" BOOLEAN DEFAULT false,
    "FLAG_SUSU" BOOLEAN DEFAULT false,
    "KODE_DESC" VARCHAR(3) DEFAULT '',
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "absent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "att_log" (
    "id" UUID NOT NULL,
    "nik" VARCHAR(20) NOT NULL DEFAULT '',
    "id_absen" VARCHAR(9) NOT NULL DEFAULT '',
    "tanggal" DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "jam" CHAR(5) NOT NULL DEFAULT '',
    "cflag" CHAR(1) NOT NULL DEFAULT '',
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "att_log_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "time_work" (
    "id" UUID NOT NULL,
    "TANGGAL" DATE NOT NULL,
    "KD_CMPY" VARCHAR(3) NOT NULL,
    "TYPE_TIME" VARCHAR(2) NOT NULL,
    "DAY_CODE" INTEGER NOT NULL DEFAULT 0,
    "SHIFT_CODE" INTEGER NOT NULL DEFAULT 0,
    "DAY_NAME" VARCHAR(20),
    "TIME_IN" VARCHAR(5),
    "TIME_OUT" VARCHAR(5),
    "STR_REST1" VARCHAR(5),
    "FNS_REST1" VARCHAR(5),
    "TTL_REST1" INTEGER DEFAULT 0,
    "STR_REST2" VARCHAR(5),
    "FNS_REST2" VARCHAR(5),
    "TTL_REST2" INTEGER DEFAULT 0,
    "STR_REST3" VARCHAR(5),
    "FNS_REST3" VARCHAR(5),
    "TTL_REST3" INTEGER DEFAULT 0,
    "TOTAL_WORK" INTEGER DEFAULT 0,
    "JM_BIASA1" INTEGER DEFAULT 0,
    "JM_BIASA2" INTEGER DEFAULT 0,
    "JM_SABTU" INTEGER DEFAULT 0,
    "JML_HARI" INTEGER DEFAULT 0,
    "LATE_TOLERANT" INTEGER DEFAULT 0,
    "ROUND_JAM" INTEGER DEFAULT 30,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "time_work_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "lembur" (
    "id" UUID NOT NULL,
    "PERIODE" VARCHAR(6) NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "TGL_LEMBUR" DATE NOT NULL,
    "NIK" VARCHAR(10),
    "NAMA" VARCHAR(30),
    "KD_CMPY" VARCHAR(3),
    "KD_FACT" VARCHAR(2),
    "KD_BAG" VARCHAR(2),
    "KD_DEPT" VARCHAR(2),
    "KD_SEKSIE" VARCHAR(6),
    "KD_JAM" VARCHAR(2),
    "KD_HARI" INTEGER DEFAULT 1,
    "KD_SHIF" INTEGER DEFAULT 1,
    "REAL_MULAI" VARCHAR(5),
    "REAL_AKHIR" VARCHAR(5),
    "PLAN_MULAI" VARCHAR(5),
    "PLAN_AKHIR" VARCHAR(5),
    "TYPE_OT" INTEGER DEFAULT 1,
    "TOT_LEMBUR" DECIMAL(6,2) DEFAULT 0.00,
    "KET_LEMBUR" VARCHAR(30),
    "LEMBUR1" DECIMAL(6,2) DEFAULT 0.00,
    "LEMBUR2" DECIMAL(6,2) DEFAULT 0.00,
    "LEMBUR3" DECIMAL(6,2) DEFAULT 0.00,
    "LEMBUR4" DECIMAL(6,2) DEFAULT 0.00,
    "approved" BOOLEAN DEFAULT false,
    "approved_by" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,
    "jnsJamKdJam" VARCHAR(2),

    CONSTRAINT "lembur_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "holiday" (
    "id" UUID NOT NULL,
    "TANGGAL" DATE NOT NULL,
    "KETERANGAN" VARCHAR(40),
    "TYPE_DAY" "TipeHari" DEFAULT 'LIBUR_NASIONAL',
    "is_repeat" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "holiday_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "desc_absen" (
    "KODE_DESC" CHAR(3) NOT NULL,
    "KETERANGAN" VARCHAR(30),
    "color_code" VARCHAR(7) DEFAULT '#000000',
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "desc_absen_pkey" PRIMARY KEY ("KODE_DESC")
);

-- CreateTable
CREATE TABLE "jnsjam" (
    "KD_JAM" VARCHAR(2) NOT NULL,
    "JNS_JAM" VARCHAR(30),
    "JMSHIF" INTEGER DEFAULT 1,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "jnsjam_pkey" PRIMARY KEY ("KD_JAM")
);

-- CreateTable
CREATE TABLE "gaji" (
    "id" UUID NOT NULL,
    "PERIOD" VARCHAR(6) NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "TGL_PROSES" DATE NOT NULL,
    "NIK" VARCHAR(10),
    "NAMA" VARCHAR(30),
    "KD_CMPY" VARCHAR(3),
    "KD_FACT" VARCHAR(2),
    "KD_BAG" VARCHAR(2),
    "KD_DEPT" VARCHAR(2),
    "KD_SEKSIE" VARCHAR(6),
    "KD_JAB" VARCHAR(3),
    "TGL_MSK" DATE NOT NULL,
    "TYPE_EMPL" INTEGER DEFAULT 0,
    "KD_PTKP" INTEGER DEFAULT 0,
    "KD_PJK" INTEGER DEFAULT 0,
    "TYPE_PJK" INTEGER DEFAULT 0,
    "KD_BPJSTK" BOOLEAN DEFAULT false,
    "KD_BPJSKES" BOOLEAN DEFAULT false,
    "KD_OUT" BOOLEAN DEFAULT false,
    "KD_JNS" INTEGER DEFAULT 0,
    "THN_KERJA" INTEGER DEFAULT 0,
    "BLN_KERJA" INTEGER DEFAULT 0,
    "HR_KERJA" INTEGER DEFAULT 0,
    "PERSENMASA" DECIMAL(5,2) DEFAULT 0.00,
    "PERSEN_RMH" DECIMAL(5,2) DEFAULT 0.00,
    "HR_KERJA1" INTEGER DEFAULT 0,
    "HR_KERJA2" INTEGER DEFAULT 0,
    "POKOK_BLN" DECIMAL(15,0) DEFAULT 0,
    "POKOK_TRM" DECIMAL(15,0) DEFAULT 0,
    "TJABATAN" DECIMAL(15,0) DEFAULT 0,
    "TTRANSPORT" DECIMAL(15,0) DEFAULT 0,
    "TKHUSUS" DECIMAL(15,0) DEFAULT 0,
    "TMAKAN" DECIMAL(15,0) DEFAULT 0,
    "TOTUSHIFT" DECIMAL(15,0) DEFAULT 0,
    "MEALOT" DECIMAL(15,0) DEFAULT 0,
    "TUNJRAPEL" DECIMAL(15,0) DEFAULT 0,
    "TUNJMEDIK" DECIMAL(15,0) DEFAULT 0,
    "TUNJLAIN" DECIMAL(15,0) DEFAULT 0,
    "ADM_BANK" DECIMAL(15,0) DEFAULT 0,
    "RAPEL" DECIMAL(15,0) DEFAULT 0,
    "TLAIN" DECIMAL(15,0) DEFAULT 0,
    "TPPH21" DECIMAL(15,0) DEFAULT 0,
    "UPAHTETAP" DECIMAL(15,0) DEFAULT 0,
    "DASAR_BPJSTK" DECIMAL(15,0) DEFAULT 0,
    "DASAR_BPJSKES" DECIMAL(15,0) DEFAULT 0,
    "DASAR_JPN" DECIMAL(15,0) DEFAULT 0,
    "JLEMBUR1" DECIMAL(6,2) DEFAULT 0.00,
    "JLEMBUR2" DECIMAL(6,2) DEFAULT 0.00,
    "JLEMBUR3" DECIMAL(6,2) DEFAULT 0.00,
    "JLEMBUR4" DECIMAL(6,2) DEFAULT 0.00,
    "TOTJLEMBUR" DECIMAL(7,2) DEFAULT 0.00,
    "LEBIHJAM" DECIMAL(7,2) DEFAULT 0.00,
    "TOTULEMBUR" DECIMAL(15,0) DEFAULT 0,
    "TOTLMBNERUS" DECIMAL(15,0) DEFAULT 0,
    "JKN_COMP" DECIMAL(14,4) DEFAULT 0.0000,
    "JKN_EMPL" DECIMAL(14,4) DEFAULT 0.0000,
    "JHT_COMP" DECIMAL(14,4) DEFAULT 0.0000,
    "JHT_EMPL" DECIMAL(14,4) DEFAULT 0.0000,
    "JPN_COMP" DECIMAL(14,4) DEFAULT 0.0000,
    "JPN_EMPL" DECIMAL(14,4) DEFAULT 0.0000,
    "HR_SHIFT1" INTEGER DEFAULT 0,
    "HR_SHIFT2" INTEGER DEFAULT 0,
    "HR_SHIFT3" INTEGER DEFAULT 0,
    "HR_SHIFT4" INTEGER DEFAULT 0,
    "HR_SHIFT5" INTEGER DEFAULT 0,
    "HR_SHIFT6" INTEGER DEFAULT 0,
    "HR_SHIFT7" INTEGER DEFAULT 0,
    "HR_SHIFT8" INTEGER DEFAULT 0,
    "HR_SHIFT9" INTEGER DEFAULT 0,
    "HR_SHIFT10" INTEGER DEFAULT 0,
    "GKOTOR" DECIMAL(15,0) DEFAULT 0,
    "GBERSIH" DECIMAL(15,0) DEFAULT 0,
    "THR" DECIMAL(15,0) DEFAULT 0,
    "PPH_THR" DECIMAL(15,0) DEFAULT 0,
    "CLOSING" BOOLEAN DEFAULT false,
    "paid_date" DATE,
    "paid_by" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "gaji_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "potongan" (
    "id" UUID NOT NULL,
    "PERIOD" VARCHAR(6) NOT NULL,
    "TRANS_ID" VARCHAR(10) NOT NULL,
    "TRANS_DATE" DATE NOT NULL,
    "TRANS_CODE" INTEGER NOT NULL DEFAULT 0,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10),
    "JUMLAH" DECIMAL(15,0) DEFAULT 0,
    "KETERANGAN" VARCHAR(50),
    "status" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "potongan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tunjangan" (
    "id" UUID NOT NULL,
    "PERIOD" VARCHAR(6) NOT NULL,
    "TRANS_ID" VARCHAR(10) NOT NULL,
    "TRANS_DATE" DATE NOT NULL,
    "TRANS_CODE" INTEGER NOT NULL DEFAULT 0,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10),
    "JUMLAH" DECIMAL(15,0) DEFAULT 0,
    "KETERANGAN" VARCHAR(50),
    "status" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "tunjangan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rapel" (
    "id" UUID NOT NULL,
    "PERIOD" VARCHAR(6) NOT NULL,
    "TRANS_ID" VARCHAR(10) NOT NULL,
    "TRANS_DATE" DATE NOT NULL,
    "TRANS_CODE" INTEGER NOT NULL DEFAULT 0,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10),
    "JUMLAH" DECIMAL(15,0) DEFAULT 0,
    "KETERANGAN" VARCHAR(50),
    "status" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "rapel_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pphthn" (
    "id" UUID NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "THPJ" VARCHAR(4) NOT NULL,
    "NPWP" VARCHAR(20) NOT NULL DEFAULT '',
    "KD_WNI" BOOLEAN DEFAULT true,
    "NIK" VARCHAR(10) NOT NULL DEFAULT '',
    "NAMA" VARCHAR(30) NOT NULL DEFAULT '',
    "ALAMAT" VARCHAR(100) NOT NULL DEFAULT '',
    "GAJI_BRUTO" DECIMAL(15,0) DEFAULT 0,
    "BIAYA_JBT" DECIMAL(15,0) DEFAULT 0,
    "PENGURANG" DECIMAL(15,0) DEFAULT 0,
    "NETTO" DECIMAL(15,0) DEFAULT 0,
    "PTKP" DECIMAL(15,0) DEFAULT 0,
    "PKP" DECIMAL(15,0) DEFAULT 0,
    "PPH21" DECIMAL(15,0) DEFAULT 0,
    "SUDAH_BAYAR" DECIMAL(15,0) DEFAULT 0,
    "KURANG_BAYAR" DECIMAL(15,0) DEFAULT 0,
    "status" BOOLEAN DEFAULT false,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "pphthn_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ptkp" (
    "KODE" INTEGER NOT NULL DEFAULT 0,
    "TYPE" VARCHAR(3) NOT NULL DEFAULT '',
    "WPAJAK" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "TKELUARGA" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "KETERANGAN" VARCHAR(20) NOT NULL DEFAULT '',
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "ptkp_pkey" PRIMARY KEY ("KODE")
);

-- CreateTable
CREATE TABLE "bataspajak" (
    "id" UUID NOT NULL,
    "BATAS1" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "BATAS2" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "PERSEN" DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    "tahun" INTEGER NOT NULL DEFAULT 2024,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "bataspajak_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "batasthr" (
    "id" UUID NOT NULL,
    "BATAS1" DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    "BATAS2" DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    "PERSEN" DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    "tahun" INTEGER NOT NULL DEFAULT 2024,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "batasthr_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "masakerja" (
    "id" UUID NOT NULL,
    "BATAS1" DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    "BATAS2" DECIMAL(4,1) NOT NULL DEFAULT 0.0,
    "VALUE" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "tahun" INTEGER NOT NULL DEFAULT 2024,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "masakerja_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "gradebonus" (
    "GRADE" CHAR(1) NOT NULL,
    "PERSEN" DECIMAL(5,2) NOT NULL,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "gradebonus_pkey" PRIMARY KEY ("GRADE")
);

-- CreateTable
CREATE TABLE "pinjamhdr" (
    "id" UUID NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "TGL_PINJAM" DATE NOT NULL,
    "TOT_PINJAM" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "JNS_SUMBER" INTEGER NOT NULL DEFAULT 0,
    "SALDO_PINJAM" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "JML_CICIL" INTEGER NOT NULL DEFAULT 0,
    "KETERANGAN" VARCHAR(100) NOT NULL DEFAULT '',
    "status" BOOLEAN DEFAULT true,
    "approved" BOOLEAN DEFAULT false,
    "approved_by" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "pinjamhdr_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pinjamdet" (
    "id" UUID NOT NULL,
    "TRANS_ID" VARCHAR(10) NOT NULL,
    "PERIODE" VARCHAR(6) NOT NULL,
    "JNS_SUMBER" INTEGER NOT NULL DEFAULT 0,
    "TGL_BAYAR" DATE NOT NULL,
    "TGL_PINJAM" DATE NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "JML_BAYAR" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "SALDO_PINJAM" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "KETERANGAN" VARCHAR(80) NOT NULL DEFAULT '',
    "FLAG_LUNAS" BOOLEAN DEFAULT false,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "pinjamdet_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "saldo_medic" (
    "id" UUID NOT NULL,
    "PERIOD" VARCHAR(6) NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "SALDO" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "saldo_medic_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "medik_trans" (
    "id" UUID NOT NULL,
    "TRANS_ID" VARCHAR(10) NOT NULL,
    "PERIOD" VARCHAR(6) NOT NULL,
    "TGL_MEDIK" DATE NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10) NOT NULL,
    "PASIEN" VARCHAR(30) NOT NULL,
    "KLINIK" VARCHAR(30) NOT NULL,
    "KODE_KLAIM" INTEGER NOT NULL DEFAULT 0,
    "BY_DOKTER" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "BY_OBAT" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "BY_LAIN" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "BY_TOTAL" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "SISA_PLAFOND" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "KETERANGAN" VARCHAR(40) NOT NULL,
    "KD_BAYAR" INTEGER NOT NULL DEFAULT 0,
    "status" BOOLEAN DEFAULT false,
    "approved" BOOLEAN DEFAULT false,
    "approved_by" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "medik_trans_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "parameter" (
    "id" UUID NOT NULL,
    "KD_CMPY" CHAR(3) NOT NULL,
    "VALID_DATE" DATE NOT NULL,
    "COMPANY" VARCHAR(30) NOT NULL DEFAULT '',
    "UMK" DECIMAL(15,0) NOT NULL DEFAULT 0,
    "UMK_REGIONAL" DECIMAL(15,0) DEFAULT 0,
    "UANG_MAKAN" DECIMAL(15,0) DEFAULT 0,
    "UANG_TRANSPORT" DECIMAL(15,0) DEFAULT 0,
    "PERSEN_BPJSTK" DECIMAL(5,2) DEFAULT 0.00,
    "PERSEN_BPJSKES" DECIMAL(5,2) DEFAULT 0.00,
    "MAX_PLAFOND_MEDIC" DECIMAL(15,0) DEFAULT 0,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "parameter_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "periode" (
    "PERIODE_ID" VARCHAR(6) NOT NULL,
    "AWAL" DATE NOT NULL,
    "AKHIR" DATE NOT NULL,
    "DATA_DEFA" BOOLEAN DEFAULT false,
    "TUTUP" BOOLEAN DEFAULT false,
    "tahun" INTEGER NOT NULL,
    "bulan" INTEGER NOT NULL,
    "nama" VARCHAR(50),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,
    "KD_CMPY" CHAR(3),

    CONSTRAINT "periode_pkey" PRIMARY KEY ("PERIODE_ID")
);

-- CreateTable
CREATE TABLE "bulan" (
    "NO" VARCHAR(2) NOT NULL,
    "NMBULAN" VARCHAR(10) NOT NULL DEFAULT '',
    "NMBULANPDK" VARCHAR(3) NOT NULL DEFAULT '',
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "bulan_pkey" PRIMARY KEY ("NO")
);

-- CreateTable
CREATE TABLE "sys_user" (
    "id" UUID NOT NULL,
    "Id" INTEGER,
    "Nik" VARCHAR(11) NOT NULL DEFAULT '',
    "Email" VARCHAR(60) NOT NULL DEFAULT '',
    "Username" VARCHAR(32) NOT NULL DEFAULT '',
    "Password" VARCHAR(64) NOT NULL DEFAULT '',
    "Name" VARCHAR(64) NOT NULL DEFAULT '',
    "PositionId" INTEGER NOT NULL DEFAULT 0,
    "Active" BOOLEAN DEFAULT true,
    "Empl_id" VARCHAR(11) NOT NULL DEFAULT '',
    "Last_login" TIMESTAMP,
    "last_ip" VARCHAR(45),
    "is_online" BOOLEAN DEFAULT false,
    "Created_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "sys_user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_menu" (
    "id" UUID NOT NULL,
    "Id" INTEGER NOT NULL,
    "modulname" VARCHAR(30) NOT NULL DEFAULT '',
    "Desc" TEXT DEFAULT '',
    "Url" VARCHAR(60) NOT NULL DEFAULT '',
    "Mark" BOOLEAN DEFAULT false,
    "Icon" VARCHAR(60) DEFAULT '',
    "order_no" INTEGER DEFAULT 0,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "sys_menu_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_submenu" (
    "id" UUID NOT NULL,
    "Id" INTEGER NOT NULL,
    "MainMenuId" INTEGER NOT NULL DEFAULT 0,
    "ModulName" VARCHAR(32) NOT NULL DEFAULT '',
    "Desc" VARCHAR(32) NOT NULL DEFAULT '',
    "URL" TEXT NOT NULL,
    "Icon" TEXT,
    "order_no" INTEGER DEFAULT 0,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "sys_submenu_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_privilege" (
    "id" UUID NOT NULL,
    "Id" INTEGER NOT NULL,
    "UserId" INTEGER DEFAULT 0,
    "PositionId" INTEGER NOT NULL DEFAULT 0,
    "modul" VARCHAR(200) NOT NULL DEFAULT '',
    "Add" BOOLEAN DEFAULT false,
    "View" BOOLEAN DEFAULT false,
    "Edit" BOOLEAN DEFAULT false,
    "Remove" BOOLEAN DEFAULT false,
    "Print" BOOLEAN DEFAULT false,
    "Approve" BOOLEAN DEFAULT false,
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "sys_privilege_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_user_position" (
    "id" UUID NOT NULL,
    "Id" INTEGER NOT NULL,
    "PositionCode" VARCHAR(11) NOT NULL DEFAULT '',
    "PositionName" VARCHAR(32) NOT NULL DEFAULT '',
    "Remark" TEXT,
    "Active" BOOLEAN DEFAULT true,
    "level" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "sys_user_position_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_notification" (
    "id" UUID NOT NULL,
    "Id" INTEGER NOT NULL,
    "CreatorUserId" INTEGER NOT NULL DEFAULT 0,
    "Type" INTEGER NOT NULL DEFAULT 0,
    "Subject" VARCHAR(60) NOT NULL DEFAULT '',
    "Note" TEXT NOT NULL,
    "Url" TEXT,
    "Status" BOOLEAN DEFAULT false,
    "is_read" BOOLEAN DEFAULT false,
    "recipient_id" INTEGER,
    "Created_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "sys_notification_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sys_event_history" (
    "id" UUID NOT NULL,
    "Id" INTEGER NOT NULL,
    "EventId" INTEGER NOT NULL DEFAULT 0,
    "Loguser" VARCHAR(20) NOT NULL DEFAULT '',
    "Modul" VARCHAR(20),
    "Action" VARCHAR(20),
    "Data" TEXT,
    "ip_address" VARCHAR(45),
    "user_agent" TEXT,
    "Datetime" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "sys_event_history_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dcuti" (
    "id" UUID NOT NULL,
    "ID" VARCHAR(10) NOT NULL,
    "EMPL_ID" VARCHAR(9),
    "TAHUN" INTEGER DEFAULT 2000,
    "NIK" VARCHAR(10),
    "JNS_CUTI" INTEGER DEFAULT 1,
    "TGL_MULAI" DATE,
    "TGL_AKHIR" DATE,
    "CUTI_PAKAI" INTEGER DEFAULT 0,
    "KETERANGAN" VARCHAR(100) DEFAULT '',
    "STATUS" "StatusCuti" DEFAULT 'PENDING',
    "REMARK" VARCHAR(100) DEFAULT '',
    "approved_by" VARCHAR(50),
    "approved_at" TIMESTAMP,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "dcuti_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "hcuti" (
    "id" UUID NOT NULL,
    "TAHUN" VARCHAR(4) NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10) NOT NULL DEFAULT '',
    "TGL_MSK" DATE NOT NULL,
    "SALDO_CUTI" INTEGER NOT NULL DEFAULT 0,
    "TOTAL_PAKAI" INTEGER NOT NULL DEFAULT 0,
    "TOTAL_SISA" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "hcuti_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "jnscuti" (
    "id" UUID NOT NULL,
    "jns_cuti" INTEGER NOT NULL,
    "kd_jnscuti" VARCHAR(3) NOT NULL DEFAULT '',
    "nm_cuti" VARCHAR(35) NOT NULL DEFAULT '',
    "jatah" INTEGER NOT NULL DEFAULT 0,
    "kode_desc" VARCHAR(3) NOT NULL DEFAULT '',
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "jnscuti_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "jnskary" (
    "id" UUID NOT NULL,
    "KD_JNS" INTEGER NOT NULL,
    "JENIS_KARY" VARCHAR(15) NOT NULL DEFAULT '',
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "jnskary_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "jnspotongan" (
    "id" UUID NOT NULL,
    "TRANS_CODE" INTEGER NOT NULL DEFAULT 0,
    "JENIS" VARCHAR(30) NOT NULL DEFAULT '',
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "jnspotongan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "jnsrapel" (
    "id" UUID NOT NULL,
    "TRANS_CODE" INTEGER NOT NULL DEFAULT 0,
    "JENIS" VARCHAR(30) NOT NULL DEFAULT '',
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "jnsrapel_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "jnstunjangan" (
    "id" UUID NOT NULL,
    "TRANS_CODE" INTEGER NOT NULL DEFAULT 0,
    "JENIS" VARCHAR(30) NOT NULL DEFAULT '',
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "jnstunjangan_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "dshift" (
    "id" UUID NOT NULL,
    "PERIODE" VARCHAR(6) NOT NULL,
    "KD_CMPY" VARCHAR(3) NOT NULL,
    "GROUP_SHIFT" VARCHAR(2) NOT NULL,
    "GROUP_NAME" VARCHAR(30) NOT NULL DEFAULT '',
    "SHIFT01" INTEGER DEFAULT 0,
    "SHIFT02" INTEGER DEFAULT 0,
    "SHIFT03" INTEGER DEFAULT 0,
    "SHIFT04" INTEGER DEFAULT 0,
    "SHIFT05" INTEGER DEFAULT 0,
    "SHIFT06" INTEGER DEFAULT 0,
    "SHIFT07" INTEGER DEFAULT 0,
    "SHIFT08" INTEGER DEFAULT 0,
    "SHIFT09" INTEGER DEFAULT 0,
    "SHIFT10" INTEGER DEFAULT 0,
    "SHIFT11" INTEGER DEFAULT 0,
    "SHIFT12" INTEGER DEFAULT 0,
    "SHIFT13" INTEGER DEFAULT 0,
    "SHIFT14" INTEGER DEFAULT 0,
    "SHIFT15" INTEGER DEFAULT 0,
    "SHIFT16" INTEGER DEFAULT 0,
    "SHIFT17" INTEGER DEFAULT 0,
    "SHIFT18" INTEGER DEFAULT 0,
    "SHIFT19" INTEGER DEFAULT 0,
    "SHIFT20" INTEGER DEFAULT 0,
    "SHIFT21" INTEGER DEFAULT 0,
    "SHIFT22" INTEGER DEFAULT 0,
    "SHIFT23" INTEGER DEFAULT 0,
    "SHIFT24" INTEGER DEFAULT 0,
    "SHIFT25" INTEGER DEFAULT 0,
    "SHIFT26" INTEGER DEFAULT 0,
    "SHIFT27" INTEGER DEFAULT 0,
    "SHIFT28" INTEGER DEFAULT 0,
    "SHIFT29" INTEGER DEFAULT 0,
    "SHIFT30" INTEGER DEFAULT 0,
    "SHIFT31" INTEGER DEFAULT 0,
    "HR_KERJA" INTEGER DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "dshift_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "groupshift" (
    "GROUP_SHIFT" VARCHAR(2) NOT NULL,
    "GROUP_NAME" VARCHAR(30) NOT NULL DEFAULT '',
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "groupshift_pkey" PRIMARY KEY ("GROUP_SHIFT")
);

-- CreateTable
CREATE TABLE "shift_allw" (
    "id" UUID NOT NULL,
    "PERIOD" VARCHAR(6) NOT NULL,
    "SPERIOD" INTEGER NOT NULL DEFAULT 1,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "SHIFT_CODE" INTEGER DEFAULT 0,
    "ALLOWANCE" DECIMAL(15,0) DEFAULT 0,
    "MEAL_ALLOW" DECIMAL(15,0) DEFAULT 0,
    "MILK_ALLOW" DECIMAL(15,0) DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "shift_allw_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "karyawan_copy" (
    "id" UUID NOT NULL,
    "EMPL_ID" VARCHAR(9) NOT NULL,
    "NIK" VARCHAR(10),
    "NAMA" VARCHAR(30),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "karyawan_copy_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "gapok_2018" (
    "id" UUID NOT NULL,
    "NIK" VARCHAR(4) DEFAULT '',
    "NAMA KARYAWAN" VARCHAR(30),
    "GAPOK" DECIMAL(12,0),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "gapok_2018_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "group_empl" (
    "id" UUID NOT NULL,
    "NIK" VARCHAR(10) NOT NULL DEFAULT '',
    "Nama" VARCHAR(30) NOT NULL DEFAULT '',
    "GROUP" VARCHAR(3) NOT NULL DEFAULT '',
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "group_empl_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "grphift" (
    "id" UUID NOT NULL,
    "NIK" VARCHAR(10) NOT NULL,
    "Nama" VARCHAR(50) NOT NULL,
    "GROUPSHIFT" VARCHAR(5) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "grphift_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rekening" (
    "id" UUID NOT NULL,
    "NIK" VARCHAR(9),
    "Nama" VARCHAR(30),
    "rekno" VARCHAR(20),
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "rekening_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "suser" (
    "id" UUID NOT NULL,
    "nama" VARCHAR(15) NOT NULL DEFAULT '',
    "kelompok" VARCHAR(10) NOT NULL DEFAULT '',
    "pwd" VARCHAR(10) NOT NULL DEFAULT '',
    "akses" VARCHAR(5) NOT NULL DEFAULT '',
    "is_active" BOOLEAN DEFAULT true,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL,

    CONSTRAINT "suser_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "AccountEmail_email_key" ON "AccountEmail"("email");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE INDEX "Account_userId_idx" ON "Account"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");

-- CreateIndex
CREATE UNIQUE INDEX "Session_sessionToken_key" ON "Session"("sessionToken");

-- CreateIndex
CREATE INDEX "Session_userId_idx" ON "Session"("userId");

-- CreateIndex
CREATE UNIQUE INDEX "company_KODE_CMPY_key" ON "company"("KODE_CMPY");

-- CreateIndex
CREATE INDEX "company_KODE_CMPY_idx" ON "company"("KODE_CMPY");

-- CreateIndex
CREATE UNIQUE INDEX "mstdept_CKD_DEPT_key" ON "mstdept"("CKD_DEPT");

-- CreateIndex
CREATE INDEX "mstdept_CKD_BAG_idx" ON "mstdept"("CKD_BAG");

-- CreateIndex
CREATE UNIQUE INDEX "mstdept_CKD_BAG_CKD_DEPT_key" ON "mstdept"("CKD_BAG", "CKD_DEPT");

-- CreateIndex
CREATE UNIQUE INDEX "mstsie_CKD_SIE_key" ON "mstsie"("CKD_SIE");

-- CreateIndex
CREATE INDEX "mstsie_CKD_BAG_CKD_DEPT_idx" ON "mstsie"("CKD_BAG", "CKD_DEPT");

-- CreateIndex
CREATE UNIQUE INDEX "mstsie_CKD_BAG_CKD_DEPT_CKD_SIE_key" ON "mstsie"("CKD_BAG", "CKD_DEPT", "CKD_SIE");

-- CreateIndex
CREATE UNIQUE INDEX "karyawan_EMPL_ID_key" ON "karyawan"("EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "karyawan_NIK_key" ON "karyawan"("NIK");

-- CreateIndex
CREATE INDEX "karyawan_KD_CMPY_idx" ON "karyawan"("KD_CMPY");

-- CreateIndex
CREATE INDEX "karyawan_KD_FACT_idx" ON "karyawan"("KD_FACT");

-- CreateIndex
CREATE INDEX "karyawan_KD_BAG_idx" ON "karyawan"("KD_BAG");

-- CreateIndex
CREATE INDEX "karyawan_KD_DEPT_idx" ON "karyawan"("KD_DEPT");

-- CreateIndex
CREATE INDEX "karyawan_KD_SEKSIE_idx" ON "karyawan"("KD_SEKSIE");

-- CreateIndex
CREATE INDEX "karyawan_KD_JAB_idx" ON "karyawan"("KD_JAB");

-- CreateIndex
CREATE INDEX "karyawan_TGL_MSK_idx" ON "karyawan"("TGL_MSK");

-- CreateIndex
CREATE INDEX "karyawan_TGL_OUT_idx" ON "karyawan"("TGL_OUT");

-- CreateIndex
CREATE INDEX "karyawan_NAMA_idx" ON "karyawan"("NAMA");

-- CreateIndex
CREATE INDEX "karyawan_NIK_idx" ON "karyawan"("NIK");

-- CreateIndex
CREATE INDEX "karyawan_KD_STS_idx" ON "karyawan"("KD_STS");

-- CreateIndex
CREATE INDEX "keluarga_EMPL_ID_idx" ON "keluarga"("EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "keluarga_CHILD_NO_EMPL_ID_key" ON "keluarga"("CHILD_NO", "EMPL_ID");

-- CreateIndex
CREATE INDEX "sekolah_EMPL_ID_idx" ON "sekolah"("EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "sekolah_EMPL_ID_CHILD_NO_key" ON "sekolah"("EMPL_ID", "CHILD_NO");

-- CreateIndex
CREATE INDEX "kursus_EMPL_ID_idx" ON "kursus"("EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "kursus_CHILD_NO_EMPL_ID_key" ON "kursus"("CHILD_NO", "EMPL_ID");

-- CreateIndex
CREATE INDEX "kerja_EMPL_ID_idx" ON "kerja"("EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "kerja_CHILD_NO_EMPL_ID_key" ON "kerja"("CHILD_NO", "EMPL_ID");

-- CreateIndex
CREATE INDEX "kontrak_EMPL_ID_idx" ON "kontrak"("EMPL_ID");

-- CreateIndex
CREATE INDEX "kontrak_TGL_MULAI_TGL_AKHIR_idx" ON "kontrak"("TGL_MULAI", "TGL_AKHIR");

-- CreateIndex
CREATE UNIQUE INDEX "kontrak_EMPL_ID_TGL_MULAI_key" ON "kontrak"("EMPL_ID", "TGL_MULAI");

-- CreateIndex
CREATE INDEX "kondite_EMPL_ID_idx" ON "kondite"("EMPL_ID");

-- CreateIndex
CREATE INDEX "kondite_TAHUN_idx" ON "kondite"("TAHUN");

-- CreateIndex
CREATE UNIQUE INDEX "kondite_CHILD_NO_EMPL_ID_key" ON "kondite"("CHILD_NO", "EMPL_ID");

-- CreateIndex
CREATE INDEX "mutasi_EMPL_ID_idx" ON "mutasi"("EMPL_ID");

-- CreateIndex
CREATE INDEX "mutasi_TGL_MUTASI_idx" ON "mutasi"("TGL_MUTASI");

-- CreateIndex
CREATE UNIQUE INDEX "mutasi_TGL_MUTASI_EMPL_ID_key" ON "mutasi"("TGL_MUTASI", "EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "pesangon_EMPL_ID_key" ON "pesangon"("EMPL_ID");

-- CreateIndex
CREATE INDEX "pesangon_TGL_BAYAR_idx" ON "pesangon"("TGL_BAYAR");

-- CreateIndex
CREATE INDEX "absent_PERIODE_idx" ON "absent"("PERIODE");

-- CreateIndex
CREATE INDEX "absent_EMPL_ID_idx" ON "absent"("EMPL_ID");

-- CreateIndex
CREATE INDEX "absent_TGL_ABSEN_idx" ON "absent"("TGL_ABSEN");

-- CreateIndex
CREATE INDEX "absent_KD_ABSEN_idx" ON "absent"("KD_ABSEN");

-- CreateIndex
CREATE INDEX "absent_KD_LMB_idx" ON "absent"("KD_LMB");

-- CreateIndex
CREATE UNIQUE INDEX "absent_EMPL_ID_TGL_ABSEN_key" ON "absent"("EMPL_ID", "TGL_ABSEN");

-- CreateIndex
CREATE INDEX "att_log_nik_idx" ON "att_log"("nik");

-- CreateIndex
CREATE INDEX "att_log_tanggal_idx" ON "att_log"("tanggal");

-- CreateIndex
CREATE UNIQUE INDEX "att_log_nik_tanggal_jam_cflag_key" ON "att_log"("nik", "tanggal", "jam", "cflag");

-- CreateIndex
CREATE INDEX "time_work_TANGGAL_idx" ON "time_work"("TANGGAL");

-- CreateIndex
CREATE INDEX "time_work_KD_CMPY_idx" ON "time_work"("KD_CMPY");

-- CreateIndex
CREATE UNIQUE INDEX "time_work_TANGGAL_KD_CMPY_TYPE_TIME_DAY_CODE_SHIFT_CODE_key" ON "time_work"("TANGGAL", "KD_CMPY", "TYPE_TIME", "DAY_CODE", "SHIFT_CODE");

-- CreateIndex
CREATE INDEX "lembur_PERIODE_idx" ON "lembur"("PERIODE");

-- CreateIndex
CREATE INDEX "lembur_EMPL_ID_idx" ON "lembur"("EMPL_ID");

-- CreateIndex
CREATE INDEX "lembur_TGL_LEMBUR_idx" ON "lembur"("TGL_LEMBUR");

-- CreateIndex
CREATE UNIQUE INDEX "lembur_EMPL_ID_TGL_LEMBUR_key" ON "lembur"("EMPL_ID", "TGL_LEMBUR");

-- CreateIndex
CREATE UNIQUE INDEX "holiday_TANGGAL_key" ON "holiday"("TANGGAL");

-- CreateIndex
CREATE INDEX "holiday_TANGGAL_idx" ON "holiday"("TANGGAL");

-- CreateIndex
CREATE INDEX "gaji_PERIOD_idx" ON "gaji"("PERIOD");

-- CreateIndex
CREATE INDEX "gaji_EMPL_ID_idx" ON "gaji"("EMPL_ID");

-- CreateIndex
CREATE INDEX "gaji_TGL_PROSES_idx" ON "gaji"("TGL_PROSES");

-- CreateIndex
CREATE INDEX "gaji_CLOSING_idx" ON "gaji"("CLOSING");

-- CreateIndex
CREATE UNIQUE INDEX "gaji_PERIOD_EMPL_ID_key" ON "gaji"("PERIOD", "EMPL_ID");

-- CreateIndex
CREATE INDEX "potongan_PERIOD_idx" ON "potongan"("PERIOD");

-- CreateIndex
CREATE INDEX "potongan_EMPL_ID_idx" ON "potongan"("EMPL_ID");

-- CreateIndex
CREATE INDEX "potongan_TRANS_DATE_idx" ON "potongan"("TRANS_DATE");

-- CreateIndex
CREATE UNIQUE INDEX "potongan_PERIOD_TRANS_ID_key" ON "potongan"("PERIOD", "TRANS_ID");

-- CreateIndex
CREATE INDEX "tunjangan_PERIOD_idx" ON "tunjangan"("PERIOD");

-- CreateIndex
CREATE INDEX "tunjangan_EMPL_ID_idx" ON "tunjangan"("EMPL_ID");

-- CreateIndex
CREATE INDEX "tunjangan_TRANS_DATE_idx" ON "tunjangan"("TRANS_DATE");

-- CreateIndex
CREATE UNIQUE INDEX "tunjangan_PERIOD_TRANS_ID_key" ON "tunjangan"("PERIOD", "TRANS_ID");

-- CreateIndex
CREATE INDEX "rapel_PERIOD_idx" ON "rapel"("PERIOD");

-- CreateIndex
CREATE INDEX "rapel_EMPL_ID_idx" ON "rapel"("EMPL_ID");

-- CreateIndex
CREATE INDEX "rapel_TRANS_DATE_idx" ON "rapel"("TRANS_DATE");

-- CreateIndex
CREATE UNIQUE INDEX "rapel_PERIOD_TRANS_ID_key" ON "rapel"("PERIOD", "TRANS_ID");

-- CreateIndex
CREATE INDEX "pphthn_EMPL_ID_idx" ON "pphthn"("EMPL_ID");

-- CreateIndex
CREATE INDEX "pphthn_THPJ_idx" ON "pphthn"("THPJ");

-- CreateIndex
CREATE UNIQUE INDEX "pphthn_EMPL_ID_THPJ_key" ON "pphthn"("EMPL_ID", "THPJ");

-- CreateIndex
CREATE INDEX "bataspajak_tahun_idx" ON "bataspajak"("tahun");

-- CreateIndex
CREATE UNIQUE INDEX "bataspajak_BATAS1_BATAS2_tahun_key" ON "bataspajak"("BATAS1", "BATAS2", "tahun");

-- CreateIndex
CREATE INDEX "batasthr_tahun_idx" ON "batasthr"("tahun");

-- CreateIndex
CREATE UNIQUE INDEX "batasthr_BATAS1_BATAS2_tahun_key" ON "batasthr"("BATAS1", "BATAS2", "tahun");

-- CreateIndex
CREATE INDEX "masakerja_tahun_idx" ON "masakerja"("tahun");

-- CreateIndex
CREATE UNIQUE INDEX "masakerja_BATAS1_BATAS2_tahun_key" ON "masakerja"("BATAS1", "BATAS2", "tahun");

-- CreateIndex
CREATE INDEX "pinjamhdr_EMPL_ID_idx" ON "pinjamhdr"("EMPL_ID");

-- CreateIndex
CREATE INDEX "pinjamhdr_TGL_PINJAM_idx" ON "pinjamhdr"("TGL_PINJAM");

-- CreateIndex
CREATE INDEX "pinjamhdr_status_idx" ON "pinjamhdr"("status");

-- CreateIndex
CREATE UNIQUE INDEX "pinjamhdr_EMPL_ID_TGL_PINJAM_TOT_PINJAM_JNS_SUMBER_key" ON "pinjamhdr"("EMPL_ID", "TGL_PINJAM", "TOT_PINJAM", "JNS_SUMBER");

-- CreateIndex
CREATE UNIQUE INDEX "pinjamhdr_EMPL_ID_TGL_PINJAM_key" ON "pinjamhdr"("EMPL_ID", "TGL_PINJAM");

-- CreateIndex
CREATE INDEX "pinjamdet_EMPL_ID_idx" ON "pinjamdet"("EMPL_ID");

-- CreateIndex
CREATE INDEX "pinjamdet_PERIODE_idx" ON "pinjamdet"("PERIODE");

-- CreateIndex
CREATE INDEX "pinjamdet_TGL_BAYAR_idx" ON "pinjamdet"("TGL_BAYAR");

-- CreateIndex
CREATE UNIQUE INDEX "pinjamdet_TRANS_ID_PERIODE_JNS_SUMBER_TGL_BAYAR_key" ON "pinjamdet"("TRANS_ID", "PERIODE", "JNS_SUMBER", "TGL_BAYAR");

-- CreateIndex
CREATE INDEX "saldo_medic_PERIOD_idx" ON "saldo_medic"("PERIOD");

-- CreateIndex
CREATE INDEX "saldo_medic_EMPL_ID_idx" ON "saldo_medic"("EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "saldo_medic_PERIOD_EMPL_ID_key" ON "saldo_medic"("PERIOD", "EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "medik_trans_TRANS_ID_key" ON "medik_trans"("TRANS_ID");

-- CreateIndex
CREATE INDEX "medik_trans_PERIOD_idx" ON "medik_trans"("PERIOD");

-- CreateIndex
CREATE INDEX "medik_trans_EMPL_ID_idx" ON "medik_trans"("EMPL_ID");

-- CreateIndex
CREATE INDEX "medik_trans_TGL_MEDIK_idx" ON "medik_trans"("TGL_MEDIK");

-- CreateIndex
CREATE INDEX "medik_trans_status_idx" ON "medik_trans"("status");

-- CreateIndex
CREATE INDEX "parameter_KD_CMPY_idx" ON "parameter"("KD_CMPY");

-- CreateIndex
CREATE INDEX "parameter_VALID_DATE_idx" ON "parameter"("VALID_DATE");

-- CreateIndex
CREATE UNIQUE INDEX "parameter_KD_CMPY_VALID_DATE_key" ON "parameter"("KD_CMPY", "VALID_DATE");

-- CreateIndex
CREATE INDEX "periode_AWAL_AKHIR_idx" ON "periode"("AWAL", "AKHIR");

-- CreateIndex
CREATE INDEX "periode_TUTUP_idx" ON "periode"("TUTUP");

-- CreateIndex
CREATE UNIQUE INDEX "sys_user_Id_key" ON "sys_user"("Id");

-- CreateIndex
CREATE UNIQUE INDEX "sys_user_Nik_key" ON "sys_user"("Nik");

-- CreateIndex
CREATE UNIQUE INDEX "sys_user_Email_key" ON "sys_user"("Email");

-- CreateIndex
CREATE UNIQUE INDEX "sys_user_Username_key" ON "sys_user"("Username");

-- CreateIndex
CREATE INDEX "sys_user_Username_idx" ON "sys_user"("Username");

-- CreateIndex
CREATE INDEX "sys_user_Email_idx" ON "sys_user"("Email");

-- CreateIndex
CREATE INDEX "sys_user_Active_idx" ON "sys_user"("Active");

-- CreateIndex
CREATE UNIQUE INDEX "sys_menu_Id_key" ON "sys_menu"("Id");

-- CreateIndex
CREATE INDEX "sys_menu_order_no_idx" ON "sys_menu"("order_no");

-- CreateIndex
CREATE INDEX "sys_menu_is_active_idx" ON "sys_menu"("is_active");

-- CreateIndex
CREATE UNIQUE INDEX "sys_submenu_Id_key" ON "sys_submenu"("Id");

-- CreateIndex
CREATE INDEX "sys_submenu_MainMenuId_idx" ON "sys_submenu"("MainMenuId");

-- CreateIndex
CREATE INDEX "sys_submenu_order_no_idx" ON "sys_submenu"("order_no");

-- CreateIndex
CREATE INDEX "sys_submenu_is_active_idx" ON "sys_submenu"("is_active");

-- CreateIndex
CREATE UNIQUE INDEX "sys_privilege_Id_key" ON "sys_privilege"("Id");

-- CreateIndex
CREATE INDEX "sys_privilege_UserId_idx" ON "sys_privilege"("UserId");

-- CreateIndex
CREATE INDEX "sys_privilege_PositionId_idx" ON "sys_privilege"("PositionId");

-- CreateIndex
CREATE INDEX "sys_privilege_is_active_idx" ON "sys_privilege"("is_active");

-- CreateIndex
CREATE UNIQUE INDEX "sys_user_position_Id_key" ON "sys_user_position"("Id");

-- CreateIndex
CREATE UNIQUE INDEX "sys_user_position_PositionCode_key" ON "sys_user_position"("PositionCode");

-- CreateIndex
CREATE INDEX "sys_user_position_PositionCode_idx" ON "sys_user_position"("PositionCode");

-- CreateIndex
CREATE INDEX "sys_user_position_Active_idx" ON "sys_user_position"("Active");

-- CreateIndex
CREATE INDEX "sys_user_position_level_idx" ON "sys_user_position"("level");

-- CreateIndex
CREATE UNIQUE INDEX "sys_notification_Id_key" ON "sys_notification"("Id");

-- CreateIndex
CREATE INDEX "sys_notification_CreatorUserId_idx" ON "sys_notification"("CreatorUserId");

-- CreateIndex
CREATE INDEX "sys_notification_Status_idx" ON "sys_notification"("Status");

-- CreateIndex
CREATE INDEX "sys_notification_is_read_idx" ON "sys_notification"("is_read");

-- CreateIndex
CREATE INDEX "sys_notification_Created_date_idx" ON "sys_notification"("Created_date");

-- CreateIndex
CREATE UNIQUE INDEX "sys_event_history_Id_key" ON "sys_event_history"("Id");

-- CreateIndex
CREATE INDEX "sys_event_history_Loguser_idx" ON "sys_event_history"("Loguser");

-- CreateIndex
CREATE INDEX "sys_event_history_Modul_idx" ON "sys_event_history"("Modul");

-- CreateIndex
CREATE INDEX "sys_event_history_Datetime_idx" ON "sys_event_history"("Datetime");

-- CreateIndex
CREATE UNIQUE INDEX "dcuti_ID_key" ON "dcuti"("ID");

-- CreateIndex
CREATE INDEX "dcuti_EMPL_ID_idx" ON "dcuti"("EMPL_ID");

-- CreateIndex
CREATE INDEX "dcuti_TAHUN_idx" ON "dcuti"("TAHUN");

-- CreateIndex
CREATE INDEX "dcuti_STATUS_idx" ON "dcuti"("STATUS");

-- CreateIndex
CREATE INDEX "dcuti_TGL_MULAI_TGL_AKHIR_idx" ON "dcuti"("TGL_MULAI", "TGL_AKHIR");

-- CreateIndex
CREATE INDEX "hcuti_TAHUN_idx" ON "hcuti"("TAHUN");

-- CreateIndex
CREATE INDEX "hcuti_EMPL_ID_idx" ON "hcuti"("EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "hcuti_TAHUN_EMPL_ID_key" ON "hcuti"("TAHUN", "EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "jnscuti_jns_cuti_key" ON "jnscuti"("jns_cuti");

-- CreateIndex
CREATE INDEX "jnscuti_is_active_idx" ON "jnscuti"("is_active");

-- CreateIndex
CREATE UNIQUE INDEX "jnskary_KD_JNS_key" ON "jnskary"("KD_JNS");

-- CreateIndex
CREATE INDEX "jnskary_is_active_idx" ON "jnskary"("is_active");

-- CreateIndex
CREATE UNIQUE INDEX "jnspotongan_TRANS_CODE_key" ON "jnspotongan"("TRANS_CODE");

-- CreateIndex
CREATE INDEX "jnspotongan_is_active_idx" ON "jnspotongan"("is_active");

-- CreateIndex
CREATE UNIQUE INDEX "jnsrapel_TRANS_CODE_key" ON "jnsrapel"("TRANS_CODE");

-- CreateIndex
CREATE INDEX "jnsrapel_is_active_idx" ON "jnsrapel"("is_active");

-- CreateIndex
CREATE UNIQUE INDEX "jnstunjangan_TRANS_CODE_key" ON "jnstunjangan"("TRANS_CODE");

-- CreateIndex
CREATE INDEX "jnstunjangan_is_active_idx" ON "jnstunjangan"("is_active");

-- CreateIndex
CREATE INDEX "dshift_PERIODE_idx" ON "dshift"("PERIODE");

-- CreateIndex
CREATE INDEX "dshift_KD_CMPY_idx" ON "dshift"("KD_CMPY");

-- CreateIndex
CREATE INDEX "dshift_GROUP_SHIFT_idx" ON "dshift"("GROUP_SHIFT");

-- CreateIndex
CREATE UNIQUE INDEX "dshift_PERIODE_KD_CMPY_GROUP_SHIFT_key" ON "dshift"("PERIODE", "KD_CMPY", "GROUP_SHIFT");

-- CreateIndex
CREATE INDEX "groupshift_is_active_idx" ON "groupshift"("is_active");

-- CreateIndex
CREATE INDEX "shift_allw_PERIOD_idx" ON "shift_allw"("PERIOD");

-- CreateIndex
CREATE INDEX "shift_allw_EMPL_ID_idx" ON "shift_allw"("EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "shift_allw_PERIOD_SPERIOD_EMPL_ID_key" ON "shift_allw"("PERIOD", "SPERIOD", "EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "karyawan_copy_EMPL_ID_key" ON "karyawan_copy"("EMPL_ID");

-- CreateIndex
CREATE UNIQUE INDEX "suser_nama_key" ON "suser"("nama");

-- AddForeignKey
ALTER TABLE "Account" ADD CONSTRAINT "Account_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mstdept" ADD CONSTRAINT "mstdept_CKD_BAG_fkey" FOREIGN KEY ("CKD_BAG") REFERENCES "mstbag"("CKD_BAG") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mstsie" ADD CONSTRAINT "mstsie_CKD_BAG_fkey" FOREIGN KEY ("CKD_BAG") REFERENCES "mstbag"("CKD_BAG") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mstsie" ADD CONSTRAINT "mstsie_CKD_DEPT_fkey" FOREIGN KEY ("CKD_DEPT") REFERENCES "mstdept"("CKD_DEPT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_KD_CMPY_fkey" FOREIGN KEY ("KD_CMPY") REFERENCES "company"("KODE_CMPY") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_KD_FACT_fkey" FOREIGN KEY ("KD_FACT") REFERENCES "mstfact"("CKD_FACT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_KD_BAG_fkey" FOREIGN KEY ("KD_BAG") REFERENCES "mstbag"("CKD_BAG") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_KD_DEPT_fkey" FOREIGN KEY ("KD_DEPT") REFERENCES "mstdept"("CKD_DEPT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_KD_SEKSIE_fkey" FOREIGN KEY ("KD_SEKSIE") REFERENCES "mstsie"("CKD_SIE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_KD_JAB_fkey" FOREIGN KEY ("KD_JAB") REFERENCES "mstjab"("CKD_JAB") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_KD_PKT_fkey" FOREIGN KEY ("KD_PKT") REFERENCES "mstpkt"("CKD_PKT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_KD_AGM_fkey" FOREIGN KEY ("KD_AGM") REFERENCES "mstagm"("CKD_AGM") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_KD_SKL_fkey" FOREIGN KEY ("KD_SKL") REFERENCES "mstskl"("CKD_SKL") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_BANK_CODE_fkey" FOREIGN KEY ("BANK_CODE") REFERENCES "bank"("BANK_CODE") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_jnsJamKdJam_fkey" FOREIGN KEY ("jnsJamKdJam") REFERENCES "jnsjam"("KD_JAM") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "karyawan" ADD CONSTRAINT "karyawan_GROUP_SHIFT_fkey" FOREIGN KEY ("GROUP_SHIFT") REFERENCES "groupshift"("GROUP_SHIFT") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "keluarga" ADD CONSTRAINT "keluarga_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sekolah" ADD CONSTRAINT "sekolah_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kursus" ADD CONSTRAINT "kursus_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kerja" ADD CONSTRAINT "kerja_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kontrak" ADD CONSTRAINT "kontrak_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "kondite" ADD CONSTRAINT "kondite_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "mutasi" ADD CONSTRAINT "mutasi_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pesangon" ADD CONSTRAINT "pesangon_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "absent" ADD CONSTRAINT "absent_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "absent" ADD CONSTRAINT "absent_KODE_DESC_fkey" FOREIGN KEY ("KODE_DESC") REFERENCES "desc_absen"("KODE_DESC") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "absent" ADD CONSTRAINT "absent_PERIODE_fkey" FOREIGN KEY ("PERIODE") REFERENCES "periode"("PERIODE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "absent" ADD CONSTRAINT "absent_KD_JAM_fkey" FOREIGN KEY ("KD_JAM") REFERENCES "jnsjam"("KD_JAM") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "att_log" ADD CONSTRAINT "att_log_nik_fkey" FOREIGN KEY ("nik") REFERENCES "karyawan"("NIK") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "time_work" ADD CONSTRAINT "time_work_KD_CMPY_fkey" FOREIGN KEY ("KD_CMPY") REFERENCES "company"("KODE_CMPY") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lembur" ADD CONSTRAINT "lembur_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lembur" ADD CONSTRAINT "lembur_PERIODE_fkey" FOREIGN KEY ("PERIODE") REFERENCES "periode"("PERIODE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "lembur" ADD CONSTRAINT "lembur_jnsJamKdJam_fkey" FOREIGN KEY ("jnsJamKdJam") REFERENCES "jnsjam"("KD_JAM") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "gaji" ADD CONSTRAINT "gaji_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "gaji" ADD CONSTRAINT "gaji_PERIOD_fkey" FOREIGN KEY ("PERIOD") REFERENCES "periode"("PERIODE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "gaji" ADD CONSTRAINT "gaji_KD_JAB_fkey" FOREIGN KEY ("KD_JAB") REFERENCES "mstjab"("CKD_JAB") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "potongan" ADD CONSTRAINT "potongan_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "potongan" ADD CONSTRAINT "potongan_TRANS_CODE_fkey" FOREIGN KEY ("TRANS_CODE") REFERENCES "jnspotongan"("TRANS_CODE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "potongan" ADD CONSTRAINT "potongan_PERIOD_fkey" FOREIGN KEY ("PERIOD") REFERENCES "periode"("PERIODE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tunjangan" ADD CONSTRAINT "tunjangan_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tunjangan" ADD CONSTRAINT "tunjangan_TRANS_CODE_fkey" FOREIGN KEY ("TRANS_CODE") REFERENCES "jnstunjangan"("TRANS_CODE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "tunjangan" ADD CONSTRAINT "tunjangan_PERIOD_fkey" FOREIGN KEY ("PERIOD") REFERENCES "periode"("PERIODE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rapel" ADD CONSTRAINT "rapel_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rapel" ADD CONSTRAINT "rapel_TRANS_CODE_fkey" FOREIGN KEY ("TRANS_CODE") REFERENCES "jnsrapel"("TRANS_CODE") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rapel" ADD CONSTRAINT "rapel_PERIOD_fkey" FOREIGN KEY ("PERIOD") REFERENCES "periode"("PERIODE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pphthn" ADD CONSTRAINT "pphthn_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pinjamhdr" ADD CONSTRAINT "pinjamhdr_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pinjamdet" ADD CONSTRAINT "pinjamdet_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pinjamdet" ADD CONSTRAINT "pinjamdet_EMPL_ID_TGL_PINJAM_fkey" FOREIGN KEY ("EMPL_ID", "TGL_PINJAM") REFERENCES "pinjamhdr"("EMPL_ID", "TGL_PINJAM") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "pinjamdet" ADD CONSTRAINT "pinjamdet_PERIODE_fkey" FOREIGN KEY ("PERIODE") REFERENCES "periode"("PERIODE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saldo_medic" ADD CONSTRAINT "saldo_medic_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "saldo_medic" ADD CONSTRAINT "saldo_medic_PERIOD_fkey" FOREIGN KEY ("PERIOD") REFERENCES "periode"("PERIODE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "medik_trans" ADD CONSTRAINT "medik_trans_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "medik_trans" ADD CONSTRAINT "medik_trans_PERIOD_fkey" FOREIGN KEY ("PERIOD") REFERENCES "periode"("PERIODE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "parameter" ADD CONSTRAINT "parameter_KD_CMPY_fkey" FOREIGN KEY ("KD_CMPY") REFERENCES "company"("KODE_CMPY") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "periode" ADD CONSTRAINT "periode_KD_CMPY_fkey" FOREIGN KEY ("KD_CMPY") REFERENCES "company"("KODE_CMPY") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sys_user" ADD CONSTRAINT "sys_user_Empl_id_fkey" FOREIGN KEY ("Empl_id") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sys_user" ADD CONSTRAINT "sys_user_PositionId_fkey" FOREIGN KEY ("PositionId") REFERENCES "sys_user_position"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sys_submenu" ADD CONSTRAINT "sys_submenu_MainMenuId_fkey" FOREIGN KEY ("MainMenuId") REFERENCES "sys_menu"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sys_privilege" ADD CONSTRAINT "sys_privilege_UserId_fkey" FOREIGN KEY ("UserId") REFERENCES "sys_user"("Id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sys_privilege" ADD CONSTRAINT "sys_privilege_PositionId_fkey" FOREIGN KEY ("PositionId") REFERENCES "sys_user_position"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sys_notification" ADD CONSTRAINT "sys_notification_CreatorUserId_fkey" FOREIGN KEY ("CreatorUserId") REFERENCES "sys_user"("Id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sys_notification" ADD CONSTRAINT "sys_notification_recipient_id_fkey" FOREIGN KEY ("recipient_id") REFERENCES "sys_user"("Id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sys_event_history" ADD CONSTRAINT "sys_event_history_Loguser_fkey" FOREIGN KEY ("Loguser") REFERENCES "sys_user"("Username") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dcuti" ADD CONSTRAINT "dcuti_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "hcuti" ADD CONSTRAINT "hcuti_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "jnscuti" ADD CONSTRAINT "jnscuti_kode_desc_fkey" FOREIGN KEY ("kode_desc") REFERENCES "desc_absen"("KODE_DESC") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dshift" ADD CONSTRAINT "dshift_KD_CMPY_fkey" FOREIGN KEY ("KD_CMPY") REFERENCES "company"("KODE_CMPY") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "dshift" ADD CONSTRAINT "dshift_GROUP_SHIFT_fkey" FOREIGN KEY ("GROUP_SHIFT") REFERENCES "groupshift"("GROUP_SHIFT") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shift_allw" ADD CONSTRAINT "shift_allw_EMPL_ID_fkey" FOREIGN KEY ("EMPL_ID") REFERENCES "karyawan"("EMPL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "shift_allw" ADD CONSTRAINT "shift_allw_PERIOD_fkey" FOREIGN KEY ("PERIOD") REFERENCES "periode"("PERIODE_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
